/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gos.visao;

import br.com.gos.controle.ClientesControle;
import br.com.gos.modelo.ClientesModelo;
import br.com.gos.util.GerenteFecha;
import javax.swing.JOptionPane;

/**
 *
 * @author dv22p
 */
public class FrmClientes extends javax.swing.JInternalFrame
{
    ClientesModelo cm = new ClientesModelo();
    ClientesControle cc = new ClientesControle();
    public int ne=0;
    private static FrmClientes frmClientes;
    public static FrmClientes mostrar()
    {
        if (frmClientes==null) 
        {
            frmClientes = new FrmClientes();
        }
        return frmClientes;
    }

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() 
    {
        initComponents();
    }
    
    public void controlesVisuais(boolean A, boolean B)
    {
        btPesquisar.setVisible(A);
        btNovo.setVisible(A);
        btSalva.setVisible(B);
        btEdita.setVisible(A);
        btExclui.setVisible(A);
        btCancela.setVisible(B);
        txtNome.setEnabled(B);
        txtCpf.setEnabled(B);
        txtEndereco.setEnabled(B);
        txtFone.setEnabled(B);
        txtEmail.setEnabled(B);
    }
    
    public void limpaCampos()
    {
        txtNome.setText(null);
        txtCpf.setText(null);
        txtEndereco.setText(null);
        txtFone.setText(null);
        txtEmail.setText(null);
    }
    
    public void carregaUltimoCliente()
    {
        cc.retornaUltimoRegistro(cm);
        txtCod.setText(cm.getId());
    }
    
    public void carregaClienteId()
    {
        if (! txtCod.getText().isEmpty()) 
        {
            cm.setId(txtCod.getText());
            cc.buscaClienteId(cm);
            txtNome.setText(cm.getNome());
            txtCpf.setText(cm.getCpf());
            txtEndereco.setText(cm.getEndereco());
            txtFone.setText(cm.getFone());
            txtEmail.setText(cm.getEmail());
            txtAlterado.setText(cm.getAlterado());
            txtResponsavel.setText(cm.getResponsavel());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalva = new javax.swing.JButton();
        btEdita = new javax.swing.JButton();
        btExclui = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtFone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAlterado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/novo.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/salvar.png"))); // NOI18N
        btSalva.setToolTipText("Salva");
        btSalva.setFocusable(false);
        btSalva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalva);

        btEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/editar.png"))); // NOI18N
        btEdita.setToolTipText("Editar");
        btEdita.setFocusable(false);
        btEdita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEdita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditaActionPerformed(evt);
            }
        });
        jToolBar1.add(btEdita);

        btExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/excluir.png"))); // NOI18N
        btExclui.setToolTipText("Excluir");
        btExclui.setFocusable(false);
        btExclui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExclui.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluiActionPerformed(evt);
            }
        });
        jToolBar1.add(btExclui);

        btCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/cancelar.png"))); // NOI18N
        btCancela.setToolTipText("Cancelar");
        btCancela.setFocusable(false);
        btCancela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        jToolBar1.add(btCancela);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        jLabel1.setText("Código");

        txtCod.setEnabled(false);

        txtNome.setEnabled(false);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        txtEndereco.setEnabled(false);
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyPressed(evt);
            }
        });

        jLabel4.setText("Endereço");

        jLabel5.setText("Fone");

        jLabel6.setText("E-mail");

        txtEmail.setEnabled(false);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setEnabled(false);
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });

        try {
            txtFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFone.setText("");
        txtFone.setEnabled(false);
        txtFone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFoneKeyPressed(evt);
            }
        });

        jLabel7.setText("Alterado");

        txtAlterado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlterado.setEnabled(false);

        jLabel8.setText("Responsável");

        txtResponsavel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome)
                                        .addComponent(txtEndereco)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlterado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlterado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        ne=0;
        controlesVisuais(false, true);
        limpaCampos();
        txtNome.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaActionPerformed
        if ((txtNome.getText().isEmpty()) || (txtCpf.getText().isEmpty()) || (txtEndereco.getText().isEmpty()) || (            txtFone.getText().isEmpty()) || (txtEmail.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Todos os campos são obrigatórios!");
        }
        else
        {
            int ok = JOptionPane.showConfirmDialog(null,"Confirma os dados?","Atenção",JOptionPane.YES_NO_OPTION);
            if (ok==JOptionPane.YES_OPTION)
            {
                cm.setNome(txtNome.getText().toUpperCase().trim());
                cm.setCpf(txtCpf.getText().toUpperCase().trim());
                cm.setEndereco(txtEndereco.getText().toUpperCase().trim());
                cm.setFone(txtFone.getText().toUpperCase().trim());
                cm.setEmail(txtEmail.getText().toLowerCase().trim());
                cm.setResponsavel(FrmPrincipal.lblUsuario.getText());
                if (ne==0)
                {
                    cc.addCliente(cm);
                    carregaUltimoCliente();
                    carregaClienteId();
                }
                else
                {
                    cm.setId(txtCod.getText());
                    cc.altCliente(cm);
                    carregaClienteId();
                }
                controlesVisuais(true, false);
            }
        }
    }//GEN-LAST:event_btSalvaActionPerformed

    private void btEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditaActionPerformed
        ne=1;
        controlesVisuais(false, true);
    }//GEN-LAST:event_btEditaActionPerformed

    private void btExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluiActionPerformed
        int exc = JOptionPane.showConfirmDialog(null,"Deseja remover?","Atenção",JOptionPane.YES_NO_OPTION);
        if (exc==JOptionPane.YES_OPTION)
        {
            cm.setId(txtCod.getText());
            cc.excCliente(cm);
            txtCod.setText(cm.getId());
            carregaUltimoCliente();
            carregaClienteId();
        }
    }//GEN-LAST:event_btExcluiActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        carregaClienteId();
        controlesVisuais(true, false);
    }//GEN-LAST:event_btCancelaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        GerenteFecha.dialogoFechaJanela(frmClientes, txtNome, btCancela);
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        btSalva.setVisible(false);
        btCancela.setVisible(false); 
        carregaUltimoCliente();
        carregaClienteId();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String i = txtCod.getText();
        FrmPesqClientes frmPesqClientes = new FrmPesqClientes(new javax.swing.JFrame(),true);
        frmPesqClientes.setVisible(true);
        if (! i.equals(txtCod.getText())) 
        {
            carregaClienteId(); 
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtCpf.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtEndereco.requestFocus();
        }        
    }//GEN-LAST:event_txtCpfKeyPressed

    private void txtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtFone.requestFocus();
        }        
    }//GEN-LAST:event_txtEnderecoKeyPressed

    private void txtFoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoneKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtFoneKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode()==10) 
        {
            btSalva.doClick();
        }
    }//GEN-LAST:event_txtEmailKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btEdita;
    private javax.swing.JButton btExclui;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtAlterado;
    public static javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtFone;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
