/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gos.visao;

import br.com.gos.controle.LojaControle;
import br.com.gos.modelo.LojaModelo;
import br.com.gos.util.GerenteFecha;
import javax.swing.JOptionPane;

/**
 *
 * @author dv22p
 */
public class FrmLoja extends javax.swing.JInternalFrame
{
    LojaModelo lm = new LojaModelo();
    LojaControle lc = new LojaControle();
    int ne=0;
    private static FrmLoja frmLoja;
    public static FrmLoja mostrar()
    {
        if (frmLoja==null) 
        {
            frmLoja = new FrmLoja();
        }
        return frmLoja;
    }

    /**
     * Creates new form FrmLoja
     */
    public FrmLoja() 
    {
        initComponents();
    }
    
    public void controlesVisuais(boolean A, boolean B)
    {
        btPesquisar.setVisible(A);
        btNovo.setVisible(A);
        btSalva.setVisible(B);
        btEdita.setVisible(A);
        btExclui.setVisible(A);
        btCancela.setVisible(B);
        txtRazao.setEnabled(B);
        txtCnpj.setEnabled(B);
        txtFone.setEnabled(B);
        txtEmail.setEnabled(B);
        txtCadastro.setEnabled(B);
        txtPgto.setEnabled(B);
        txtMensagem.setEnabled(B);
        ckBloquear.setEnabled(B);
    }
    
    public void limpaCampos()
    {
        txtRazao.setText(null);
        txtCnpj.setText(null);
        txtFone.setText(null);
        txtEmail.setText(null);
        txtCadastro.setText(null);
        txtPgto.setText(null);
        txtMensagem.setText(null);
        ckBloquear.setSelected(false);
    }
    
    public void carregaUltimaLoja()
    {
        lc.retornaUltimoRegistro(lm);
        txtCod.setText(lm.getId());
    }
    
    public void carregaLojaId()
    {
        if (! txtCod.getText().isEmpty()) 
        {
            lm.setId(txtCod.getText());
            lc.buscaLojaId(lm);
            txtRazao.setText(lm.getNome());
            txtCnpj.setText(lm.getCnpj());
            txtFone.setText(lm.getFone());
            txtEmail.setText(lm.getEmail());
            txtCadastro.setText(lm.getCadastro());
            txtPgto.setText(lm.getPgto());
            txtMensagem.setText(lm.getMensagem());
            if (lm.getBloqueado().equals("0"))
            {
                ckBloquear.setSelected(false);
            }
            else
            {
                ckBloquear.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalva = new javax.swing.JButton();
        btEdita = new javax.swing.JButton();
        btExclui = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPgto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        txtCadastro = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        ckBloquear = new javax.swing.JCheckBox();
        txtFone = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lojas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/novo.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/salvar.png"))); // NOI18N
        btSalva.setToolTipText("Salva");
        btSalva.setFocusable(false);
        btSalva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalva);

        btEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/editar.png"))); // NOI18N
        btEdita.setToolTipText("Editar");
        btEdita.setFocusable(false);
        btEdita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEdita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditaActionPerformed(evt);
            }
        });
        jToolBar1.add(btEdita);

        btExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/excluir.png"))); // NOI18N
        btExclui.setToolTipText("Excluir");
        btExclui.setFocusable(false);
        btExclui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExclui.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluiActionPerformed(evt);
            }
        });
        jToolBar1.add(btExclui);

        btCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/cancelar.png"))); // NOI18N
        btCancela.setToolTipText("Cancelar");
        btCancela.setFocusable(false);
        btCancela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        jToolBar1.add(btCancela);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        jLabel1.setText("Código");

        txtCod.setEnabled(false);

        jLabel2.setText("Razão Social");

        txtRazao.setEnabled(false);
        txtRazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazaoKeyPressed(evt);
            }
        });

        jLabel3.setText("CNPJ");

        jLabel4.setText("Fone");

        jLabel5.setText("E-mail");

        txtEmail.setEnabled(false);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        jLabel6.setText("Cadastrado");

        txtPgto.setEnabled(false);
        txtPgto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPgtoKeyPressed(evt);
            }
        });

        jLabel7.setText("Pagamento");

        jLabel8.setText("Mensagem");

        txtMensagem.setEnabled(false);

        try {
            txtCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadastro.setText("");
        txtCadastro.setEnabled(false);
        txtCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadastroKeyPressed(evt);
            }
        });

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setEnabled(false);
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnpjKeyPressed(evt);
            }
        });

        ckBloquear.setText("Bloquear");
        ckBloquear.setEnabled(false);

        try {
            txtFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFone.setEnabled(false);
        txtFone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFoneKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBloquear)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRazao)
                        .addComponent(txtMensagem)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPgto)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(ckBloquear)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        ne=0;
        controlesVisuais(false, true);
        limpaCampos();
        txtRazao.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaActionPerformed
        if ((txtRazao.getText().isEmpty()) || (txtEmail.getText().isEmpty()) || (txtFone.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Todos os campos são obrigatórios!");
        }
        else
        {
            int ok = JOptionPane.showConfirmDialog(null,"Confirma os dados?","Atenção",JOptionPane.YES_NO_OPTION);
            if (ok==JOptionPane.YES_OPTION)
            {
                String dia,mes,ano,dataFormatada;
                dia=txtCadastro.getText().substring(0, 2);
                mes=txtCadastro.getText().substring(3, 5);
                ano=txtCadastro.getText().substring(6);
                dataFormatada=ano+"-"+mes+"-"+dia;
                lm.setNome(txtRazao.getText().toUpperCase().trim());
                lm.setCnpj(txtCnpj.getText().toUpperCase().trim());
                lm.setFone(txtFone.getText().toUpperCase().trim());
                lm.setEmail(txtEmail.getText().toLowerCase().trim());
                lm.setCadastro(dataFormatada);
                lm.setPgto(txtPgto.getText().trim());
                lm.setMensagem(txtMensagem.getText().toUpperCase().trim());
                if (! ckBloquear.isSelected())
                {
                    lm.setBloqueado("0");
                } 
                else
                {
                    lm.setBloqueado("1");
                }
                if (ne==0)
                {
                    lc.addLoja(lm);
                    carregaUltimaLoja();
                    carregaLojaId();
                }
                else
                {
                    lm.setId(txtCod.getText());
                    lc.altLoja(lm);
                    carregaLojaId();
                }
                controlesVisuais(true, false);
            }
        }
    }//GEN-LAST:event_btSalvaActionPerformed

    private void btEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditaActionPerformed
        ne=1;
        controlesVisuais(false, true);
    }//GEN-LAST:event_btEditaActionPerformed

    private void btExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluiActionPerformed
        int exc = JOptionPane.showConfirmDialog(null,"Deseja remover?","Atenção",JOptionPane.YES_NO_OPTION);
        if (exc==JOptionPane.YES_OPTION)
        {
            lm.setId(txtCod.getText());
            lc.excLoja(lm);
            txtCod.setText(lm.getId());
            carregaUltimaLoja();
            carregaLojaId();
        }
    }//GEN-LAST:event_btExcluiActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        carregaLojaId();
        controlesVisuais(true, false);
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String i = txtCod.getText();
        FrmPesqLojas frmPesqLojas = new FrmPesqLojas(new javax.swing.JFrame(),true);
        frmPesqLojas.setVisible(true);
        if (! i.equals(txtCod.getText())) 
        {
            carregaLojaId(); 
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        btSalva.setVisible(false);
        btCancela.setVisible(false); 
        carregaUltimaLoja();
        carregaLojaId();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        GerenteFecha.dialogoFechaJanela(frmLoja, txtRazao, btCancela);
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtRazaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazaoKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtCnpj.requestFocus();
        }
    }//GEN-LAST:event_txtRazaoKeyPressed

    private void txtCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtFone.requestFocus();
        }
    }//GEN-LAST:event_txtCnpjKeyPressed

    private void txtFoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoneKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtFoneKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtCadastro.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadastroKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtPgto.requestFocus();
        }
    }//GEN-LAST:event_txtCadastroKeyPressed

    private void txtPgtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPgtoKeyPressed
        if (evt.getKeyCode()==10)
        {
            txtMensagem.requestFocus();
        }
    }//GEN-LAST:event_txtPgtoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btEdita;
    private javax.swing.JButton btExclui;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalva;
    private javax.swing.JCheckBox ckBloquear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFormattedTextField txtCadastro;
    private javax.swing.JFormattedTextField txtCnpj;
    public static javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFone;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtPgto;
    private javax.swing.JTextField txtRazao;
    // End of variables declaration//GEN-END:variables
}
