/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gos.visao;

import br.com.gos.controle.OsControle;
import br.com.gos.modelo.OsModelo;
import br.com.gos.util.GerenteFecha;
import br.com.gos.util.GerenteImprime;
import static br.com.gos.visao.FrmPrincipal.numeroLoja;
import javax.swing.JOptionPane;

/**
 *
 * @author dv22p
 */
public class FrmOs extends javax.swing.JInternalFrame
{
    GerenteImprime gerenteImprime;
    OsModelo om = new OsModelo();
    OsControle oc = new OsControle();
    int ne=0;
    private static FrmOs frmOs;
    public static FrmOs mostrar()
    {
        if (frmOs==null) 
        {
            frmOs = new FrmOs();
        }
        return frmOs;
    }

    /**
     * Creates new form FrmOs
     */
    public FrmOs()
    {
        initComponents();
        gerenteImprime = new GerenteImprime();
    }

    public void controlesVisuais(boolean A, boolean B)
    {
        btPesquisar.setVisible(A);
        btImprime.setVisible(A);
        btNovo.setVisible(A);
        btSalva.setVisible(B);
        btEdita.setVisible(A);
        btExclui.setVisible(A);
        btCancela.setVisible(B);
        cbxTipo.setEnabled(B);
        cbxSituacao.setEnabled(B);
        txtEquipamento.setEnabled(B);
        txtDefeito.setEnabled(B);
        txtServico.setEnabled(B);
        txtPrevisao.setEnabled(B);
        txtValor.setEnabled(B);
    }
    
    public void limpaCampos()
    {
        txtEmissao.setText(null);
        txtCodCliente.setText(null);
        txtNomeCliente.setText(null);
        txtEquipamento.setText(null);
        txtDefeito.setText(null);
        txtServico.setText(null);
        txtPrevisao.setText(null);
        txtValor.setText(null);
        txtAlterado.setText(null);
        txtResponsavel.setText(null);
    }
    
    public void carregaUltimaOs()
    {
        oc.retornaUltimoRegistro(om);
        txtCod.setText(om.getOs());
    }
    
    public void carregaOs()
    {
        if (! txtCod.getText().isEmpty()) 
        {
            om.setOs(txtCod.getText());
            oc.buscaOs(om);
            txtEmissao.setText(om.getEmissao());
            txtCodCliente.setText(om.getIdCliente());
            txtNomeCliente.setText(om.getNomeCliente());
            cbxTipo.setSelectedItem(om.getTipo());
            cbxSituacao.setSelectedItem(om.getSituacao());
            txtEquipamento.setText(om.getEquipamento());
            txtDefeito.setText(om.getDefeito());
            txtServico.setText(om.getServico());
            txtPrevisao.setText(om.getEntrega());
            txtValor.setText(om.getValor().replace(".", ","));
            txtAlterado.setText(om.getAlterado());
            txtResponsavel.setText(om.getResponsavel());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btImprime = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btSalva = new javax.swing.JButton();
        btEdita = new javax.swing.JButton();
        btExclui = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmissao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        cbxSituacao = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDefeito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAlterado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        txtPrevisao = new javax.swing.JFormattedTextField();

        jLabel12.setText("Nome do Cliente");

        jTextField7.setText("jTextField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ordem de Serviço");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btImprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/imprimir.png"))); // NOI18N
        btImprime.setToolTipText("Imprimir");
        btImprime.setFocusable(false);
        btImprime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimeActionPerformed(evt);
            }
        });
        jToolBar1.add(btImprime);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/novo.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/salvar.png"))); // NOI18N
        btSalva.setToolTipText("Salva");
        btSalva.setFocusable(false);
        btSalva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalva);

        btEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/editar.png"))); // NOI18N
        btEdita.setToolTipText("Editar");
        btEdita.setFocusable(false);
        btEdita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEdita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditaActionPerformed(evt);
            }
        });
        jToolBar1.add(btEdita);

        btExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/excluir.png"))); // NOI18N
        btExclui.setToolTipText("Excluir");
        btExclui.setFocusable(false);
        btExclui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExclui.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluiActionPerformed(evt);
            }
        });
        jToolBar1.add(btExclui);

        btCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/cancelar.png"))); // NOI18N
        btCancela.setToolTipText("Cancelar");
        btCancela.setFocusable(false);
        btCancela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });
        jToolBar1.add(btCancela);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gos/icones/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(btPesquisar);

        jLabel1.setText("Código");

        txtCod.setEnabled(false);

        jLabel2.setText("Emissão");

        txtEmissao.setEnabled(false);

        jLabel3.setText("Tipo");

        jLabel4.setText("Situção");

        jLabel5.setText("Equipamento");

        txtEquipamento.setEnabled(false);
        txtEquipamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEquipamentoKeyPressed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORÇAMENTO", "ORDEM DE SERVIÇO" }));
        cbxTipo.setEnabled(false);

        cbxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANCADA", "ENTREGA OK", "ORÇAMENTO REPROVADO", "AGUARDANDO APROVAÇÃO", "AGUARDANDO PEÇAS", "ABANDONADO PELO CLIENTE", "RETORNOU" }));
        cbxSituacao.setEnabled(false);

        jLabel8.setText("Serviço");

        txtServico.setEnabled(false);
        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });
        txtServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtServicoKeyPressed(evt);
            }
        });

        jLabel10.setText("Defeito");

        txtDefeito.setEnabled(false);
        txtDefeito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDefeitoKeyPressed(evt);
            }
        });

        jLabel11.setText("Previsão Entrega");

        jLabel6.setText("Cód. Cliente");

        txtCodCliente.setEnabled(false);

        jLabel7.setText("Valor do Serviço");

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setEnabled(false);
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        jLabel9.setText("Nome do Cliente");

        txtNomeCliente.setEnabled(false);

        jLabel13.setText("Alterado");

        txtAlterado.setEnabled(false);

        jLabel14.setText("Responsável");

        txtResponsavel.setEnabled(false);

        try {
            txtPrevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPrevisao.setEnabled(false);
        txtPrevisao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrevisaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAlterado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtServico)
                    .addComponent(txtDefeito)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtEquipamento)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(txtPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlterado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        ne=0;
        controlesVisuais(false, true);
        limpaCampos();
        FrmPesqClientes.clienteOs=1;
        FrmPesqClientes frmPesqClientes = new FrmPesqClientes(new javax.swing.JFrame(), true);
        frmPesqClientes.setVisible(true);
        FrmPesqClientes.clienteOs=0;
        if (txtCodCliente.getText().isEmpty())
        {
            btCancela.doClick();
        }
        txtEquipamento.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaActionPerformed
        if ((txtNomeCliente.getText().isEmpty()) || (txtEquipamento.getText().isEmpty()) || (txtDefeito.getText().             isEmpty()) || (txtServico.getText().isEmpty()) || (txtPrevisao.getText().isEmpty()) || (txtValor.getText().            isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Todos os campos são obrigatórios!");
        }
        else
        {
            int ok = JOptionPane.showConfirmDialog(null,"Confirma os dados?","Atenção",JOptionPane.YES_NO_OPTION);
            if (ok==JOptionPane.YES_OPTION)
            {
                String dia,mes,ano,dataFormatada;
                dia=txtPrevisao.getText().substring(0, 2);
                mes=txtPrevisao.getText().substring(3, 5);
                ano=txtPrevisao.getText().substring(6);
                dataFormatada=ano+"-"+mes+"-"+dia;
                om.setIdCliente(txtCodCliente.getText());
                om.setNomeCliente(txtNomeCliente.getText());
                om.setTipo(cbxTipo.getSelectedItem().toString());
                om.setSituacao(cbxSituacao.getSelectedItem().toString());
                om.setEquipamento(txtEquipamento.getText().toUpperCase().trim());
                om.setDefeito(txtDefeito.getText().toUpperCase().trim());
                om.setServico(txtServico.getText().toUpperCase().trim());
                om.setEntrega(dataFormatada);
                om.setValor(txtValor.getText().replace(",", "."));
                om.setResponsavel(FrmPrincipal.lblUsuario.getText());
                if (ne==0)
                {
                   oc.addOs(om);
                   carregaUltimaOs();
                   carregaOs();
                }
                else
                {
                   om.setOs(txtCod.getText());
                   oc.altOs(om);
                   carregaOs();
                }
                controlesVisuais(true, false);
                int i = JOptionPane.showConfirmDialog(null,"Deseja Imprimir?","Atenção",JOptionPane.YES_NO_OPTION);
                if (i==JOptionPane.YES_OPTION)
                {
                   btImprime.doClick();
                }    
            }
        }
    }//GEN-LAST:event_btSalvaActionPerformed

    private void btEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditaActionPerformed
        ne=1;
        controlesVisuais(false, true);
    }//GEN-LAST:event_btEditaActionPerformed

    private void btExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluiActionPerformed
        int exc = JOptionPane.showConfirmDialog(null,"Deseja remover?","Atenção",JOptionPane.YES_NO_OPTION);
        if (exc==JOptionPane.YES_OPTION)
        {
            om.setOs(txtCod.getText());
            oc.excOs(om);
            txtCod.setText(om.getOs());
            carregaUltimaOs();
            carregaOs();
        }
    }//GEN-LAST:event_btExcluiActionPerformed

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        carregaOs();
        controlesVisuais(true, false);
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String i = txtCod.getText();
        FrmPesqOs frmPesqOs = new FrmPesqOs(new javax.swing.JFrame(),true);
        frmPesqOs.setVisible(true);
        if (! i.equals(txtCod.getText()))
        {
            carregaOs();
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        btSalva.setVisible(false);
        btCancela.setVisible(false); 
        carregaUltimaOs();
        carregaOs();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        GerenteFecha.dialogoFechaJanela(frmOs, txtEquipamento, btCancela);
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtEquipamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipamentoKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtDefeito.requestFocus();
        }    
    }//GEN-LAST:event_txtEquipamentoKeyPressed

    private void txtDefeitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDefeitoKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtServico.requestFocus();
        }
    }//GEN-LAST:event_txtDefeitoKeyPressed

    private void txtServicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServicoKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtPrevisao.requestFocus();
        }
    }//GEN-LAST:event_txtServicoKeyPressed

    private void txtPrevisaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrevisaoKeyPressed
        if (evt.getKeyCode()==10) 
        {
            txtValor.requestFocus();
        }
    }//GEN-LAST:event_txtPrevisaoKeyPressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        if (evt.getKeyCode()==10) 
        {
            btSalva.doClick();
        }
    }//GEN-LAST:event_txtValorKeyPressed

    private void btImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimeActionPerformed
        gerenteImprime.imprimir2(Integer.parseInt(numeroLoja),Integer.parseInt(txtCod.getText()),"C:\\gos\\report\\os.jasper");
    }//GEN-LAST:event_btImprimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btEdita;
    private javax.swing.JButton btExclui;
    private javax.swing.JButton btImprime;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalva;
    private javax.swing.JComboBox<String> cbxSituacao;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtAlterado;
    public static javax.swing.JTextField txtCod;
    public static javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtDefeito;
    private javax.swing.JTextField txtEmissao;
    private javax.swing.JTextField txtEquipamento;
    public static javax.swing.JTextField txtNomeCliente;
    private javax.swing.JFormattedTextField txtPrevisao;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtServico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
